version: '3.7'

services:
  runner:
    image: tesseract-runner:${DOCKER_TAG:-latest}
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - .:/project:cached
    environment:
      HISTFILE: /project/.bash_history
      EDITOR: vi
      TESLANG: eng
